UF_CHOICES = (
    ('AC', 'ACRE'),
    ('AL', 'ALAGOAS'),
    ('AP', 'APMAPÁ'),
    ('AM', 'AMAZONAS'),
    ('BA', 'BAHIA'),
    ('CE', 'CEARÁ'),
    ('DF', 'DISTRITO FEDERAL'),
    ('ES', 'ESPRÍRITO SANTO'),
    ('GO', 'GOIÁS'),
    ('MA', 'MARANHÃO'),
    ('MS', 'MATO GROSSO DO SUL'),
    ('MT', 'MATO GROSSO'),
    ('MG', 'MINAS GERAIS'),
    ('PA', 'PARÁ'),
    ('PB', 'PARAÍBA'),
    ('PR', 'PARANÁ'),
    ('PE', 'PERNAMBUCO'),
    ('PI', 'PIAUÍ'),
    ('RJ', 'RIO DE JANEIRO'),
    ('RN', 'RIO GRANDE DO NORTE'),
    ('RS', 'RIO GRANDE DO SUL'),
    ('RO', 'RÔNDONIA'),
    ('RR', 'RORAIMA'),
    ('SC', 'SANTA CATARINA'),
    ('SP', 'SÃO PAULO'),
    ('SE', 'SERGIPE'),
    ('TO', 'TOCANTINS'),
)

RACE_CHOICE = (
    ('Amarelo', 'Amarelo'),
    ('Branco', 'Branco'),
    ('Indígena', 'Indígena'),
    ('Negro', 'Negro'),
    ('Pardo', 'Pardo'),
)
